[[appendixb]]

[appendix]
== Frequently Asked Questions

This is a list of questions asked on the mailing lists for which there really is no section in the documentation covering the subject.

[[appendixb_info]]

=== Sources of Information

[[appendixb_info_where]]

==== Q: Where&rsquo;s the FAQ?

A: You&rsquo;re looking at it. The most up-to-date copy can be found link:$$http://wiki.gnucash.org/wiki/FAQ$$[within the GnuCash Wiki].

[[appendixb_info_mail]]

==== Q: Are there mailing lists for GnuCash?

A: Yes. Go to link:$$http://lists.gnucash.org/mailman/listinfo/gnucash-user$$[http://lists.gnucash.org/mailman/listinfo/gnucash-user] and link:$$http://lists.gnucash.org/mailman/listinfo/gnucash-devel$$[http://lists.gnucash.org/mailman/listinfo/gnucash-devel] to subscibe.

[[appendixb_info_mailarchive]]

==== Q: Is there a searchable archive for the mailing lists?

A: Yes, you can search the mail list archives at link:$$http://news.gmane.org/gmane.comp.gnome.apps.gnucash.devel$$[] and link:$$http://news.gmane.org/gmane.comp.gnome.apps.gnucash.user$$[] (and link:$$http://news.gmane.org/gmane.comp.gnome.apps.gnucash.german$$[] if you speak German).

[[appendixb_info_other]]

==== Q: Are there other means of obtaining support for GnuCash?

A: Yes. Many of the developers hang out on icq in the #gnucash discussion on irc.gnome.org. Also, there is a wiki online at link:$$http://wiki.gnucash.org/wiki/GnuCash$$[http://wiki.gnucash.org/wiki/GnuCash].

[[appendixb_general]]

=== General Information

[[appendixb_software_windows]]

==== Q: Can I run GnuCash on Windows?

A: Yes. Starting with release 2.2.0, GnuCash is also available on Windows.

Other related options would be colinux, VMWare and a windows-based X-server hosting a remote GnuCash session.

[[appendixb_general_hard2compile]]

==== Q: I heard it is too hard to compile GnuCash!

A: This was probably true at the time when 1.6.0 was released. It is no longer true today, as almost every distribution ships with all the necessary libraries (except g-wrap, which means there is in fact "one" extra library to be installed before compiling GnuCash). However, by default, distributions won&rsquo;t install the development packages of the required libraries, so you might need to start your distribution&rsquo;s installer program and tell it to install not only the library packages but also the -devel packages. In general, it was noted that this problem concerns many applications in the gnome domain, and this also boils down to the fact that there is no such thing as "one monolithic gnome package".

[[appendixb_general_batchmode]]

==== Q: Is there a batch mode (non-interactive) available for GnuCash, for building reports, etc?

A: No, for now GnuCash must be run interactively.

[[appendixb_general_multuser]]

==== Q: Can multiple people access the same datafile in GnuCash?

A: You can have multiple people with access to the same datafile, but they cannot use the data file simultaneously.

To setup multi-person access, all the people must have read/write access to the directory containing the file (to read the other&rsquo;s created files, and to create new files).  One way to do this is by creating a user group and setting the data directory to be owned by the shared group and set to mode 2775. The "2" makes the directory setgid which copies the permissions to all files.

[[appendixb_general_WhyC]]

==== Q: Why is GnuCash written in C?

A: The core functionality of GnuCash is written in C, but do not forget that much of this can be accessed through Guile (scheme).  There are a number of reasons for why GnuCash is written in C.  The first is historical, GnuCash was started in 1996 (or maybe even earlier!) and many of the OOP (C++, Java, Python) compilers were not yet mature and standarized enough on the variety of platforms considered at that time, so C was the only option at that time.  A second reason is because the standard GUI GnuCash uses is GTK, which is written in C.

[[appendixb_general_rewrite]]

==== Q: Why don&rsquo;t you rewrite GnuCash in programming language xyz so that I can contribute easily?

A: The quick answer is "We won&rsquo;t". The longer answer is complex but still amounts to "We won&rsquo;t". GnuCash is a large body of code maintained by a small group of developers who are comfortable in C and Scheme (Guile). Actually, 80% of it is in C and approx. 13% is in Scheme/Lisp. There is no valid reason that would justify rewriting this amount of existing code in a newer language. Also, creating language bindings to recent languages such as Python or Ruby or (insert your favourite language here) is labor intensive, and we&rsquo;re already stretched pretty thin maintaining and developing the existing code.

Having said that, this is an open source project and you&rsquo;re free to do with it or contribute what you want. Just don&rsquo;t expect much support if the reason for your changes is that you&rsquo;re not willing to learn C or Scheme. Also, GnuCash used to have SWIG bindings (link:$$http://www.swig.org$$[]) which have been used for some perl programming code. According to a list discussion, these SWIG bindings might still be a way to include other languages into GnuCash, but currently they are unused and unmaintained.

[[appendixb_general_newFeatures]]

==== Q: I really want feature XYZ but GnuCash doesn&rsquo;t have it. How do I get it added?

A: Ask nicely. :-) You can file an enhancement request at link:$$http://bugzilla.gnome.org/enter_bug.cgi?product=GnuCash$$[]. Please bear in mind to describe your proposed enhancement as verbosely as possible. The trick here is to learn how to give the best information to the programmers about what your proposed new feature should do. If you want to speed up development significantly, consider donating some money as described on GnuCashDevelopment.

[[appendixb_software_web]]

==== Q: Is there a web interface available for GnuCash?

A: No

[[appendixb_software_security]]

==== Q: How can I provide security for GnuCash data using CFS, etc.)

A: Unanswered

[[appendixb_software_contribute]]

==== Q: How can I contribute to the GnuCash project?

A: We&rsquo;re working on a more formal process, but for now you should subscribe to the mailing list at link:$$http://lists.gnucash.org/mailman/listinfo/gnucash-user$$[http://lists.gnucash.org/mailman/listinfo/gnucash-user] and link:$$http://lists.gnucash.org/mailman/listinfo/gnucash-devel$$[http://lists.gnucash.org/mailman/listinfo/gnucash-devel] and discuss what you can contribute with the participants on the lists. Please be aware that GnuCash is a large body of code written in C and Scheme (see the FAQ above, "Why is GnuCash written in C?" if you want to know why). If these are languages that you are not willing to work with, consider contributing in other ways.

[[appendixb_software_bugs]]

==== Q: I think I found a bug. How do I report it?

A: First of all, try to verify that it is indeed a bug and that it has not been reported before. Search the mail list archives (see FAQ above). Then search the link:$$http://bugzilla.gnome.org$$[Gnome Bugzilla] database.

If you feel you have indeed found a bug, you can then report it at link:$$http://bugzilla.gnome.org/enter_bug.cgi?product=GnuCash$$[]. Please bear in mind to report your bug as verbosely as possible. The trick here is to learn how to give the best information to the programmers about how to reproduce bugs. A Programmer will usually only be able to fix a bug they can see, if you can&rsquo;t make the programmer see your bug, it won&rsquo;t get fixed!

[[appendixb_using]]

=== Using GnuCash

[[appendixb_using_moveAtoB]]

==== Q: How can I move the transactions from account "A" into account "B", thus combining them?

A: At present, GnuCash does not offer a way to move groups of splits from one account to another. You will need to move them one at a time. Open the register for account "A" and select the pulldown menu item menu:View[Transaction Journal] to expose all the splits.  For every split where the "Account" field shows account "A" reset it to account "B". To do this quickly and safely, first use CtrlC to copy the destination account name ("account B") to the clipboard.  Then highlight each reference to account "A" by double clicking on it and use CtrlV to paste the destination account name.  Pressing Enter after each paste, silently moves the transaction out of the register.

Be careful!  If you inadvertently set the "Account" field to an unintended location, you will need to search through all your accounts to find the lost transaction to correct your mistake.

[[appendixb_using_merge2files]]

==== Q: Is it possible to merge two GnuCash files?

A: At present this is not possible.

[[appendixb_using_SaveAcctTemplate]]

==== Q: How can I save a template of my account structure?

A: This is available from the menu: menu:File[Export &gt; Export Accounts]

[[appendixb_using_ListAll]]

==== Q: When I search for customers (or anything else for that matter), how can I return a list of everything?

A: Enter a search criteria of matches regex, and place a single dot "." in the text field area. Then, click Find. The regular expression "." means to match anything.

[[appendixb_using_Dates]]

==== Q: How can I record a transaction on different dates (actual date and bank date)?

A: You record the transaction on the date you write the check or initiate the transaction.  When it "clears" the bank, you can click in the "Reconciled" field to "clear" the transaction (change the "n"on-reconciled to "c"leared).

[[appendixb_accounting]]

=== Accounting

[[appendixb_accounting_Taxes]]

==== Q: How do I treat taxes?  As an account payable or as an expense?

A: This is a loaded question, and you should really talk to your accountant.  How you treat taxes really depends on what kind of taxes they are, and how you WANT to treat them..  In some cases they are expenses, in some cases they are liabilities.

