[[ch_reports]]

== Reports

GnuCash is a powerful double entry accounting software package that allows
users to enter and track their money in a reliable manner. However, putting
this information into GnuCash is only a part of the process. To be truly
helpful, you need to be able to extract this information in meaningful ways.
GnuCash's reporting features allow you to just that.

GnuCash's reporting features allow you to display nearly any group of
transactions in a wide variety of formats. This makes it easy to answer
questions about your finances, such as "How much did I spend on groceries
last month?" or "How much did I earn in the previous six months?"

GnuCash includes a number of common report types, which can be modified to
meet your specific needs. If these common reports are insufficient, it is
possible to modify or even write your own custom reports (although this is
not recommended for beginners).

[[rpt_concepts]]

=== Overview

There are many standard reports pre-built in GnuCash,
all available from the  pulldown menu in the main account window.

When you select a report from the list of reports, that report is first run
with its default settings. Once you have opened the report, you can modify its parameters by clicking on
the Options button on the toolbar. Under Options, you will see the different
settings that you can change for each report. Note that for different reports,
the options will be different. 

[[rpt_savedconfigsinfo]]

=== Saved Reports Configurations Concepts

Once you have modified a report to meet your needs, you may wish to save
that report for reuse at a later point. GnuCash allows custom
reports to be saved, using the Save Report Configuration command.

To save a report configuration:



** Go to the Reports Menu and choose the desired report.

** Change the settings on the report until it includes what is needed.

** Go to the General tab of the report's options and change the Report Name
to something meaningful (Do not confuse this with the Report Title).

** Apply the changes and close the dialog.

** Click the Save Report Configuration or Save Report Configuration As... button


This will store the report options in a file in your home directory.

The first time you save a report with a name that has not already been saved,
you can use either the Save Report Configuration or the Save Report
Configuration As... button. You can modify the report name before saving it.

Once a report has been saved with the current name, the Save Report Configuration button will immediately update the saved report configuration.
Use the Save Report Configuration As button to save the current report
configuration with a new name.

Saved report configurations are available for use under the
Reports-&gt;Saved Report Configurations entry. They will also be available for
use on multicolumn reports.

Saved report configurations can be deleted in the Saved Report Configurations
dialog by clicking the trashcan icon.

To edit saved report configurations, open the report via Reports-&gt;Saved Report
Configurations, edit and apply the new options, and click Save Report
Configuration.

[[rpt_standardrpts]]

=== Standard Reports Overview

The standard reports that are included in GnuCash are presented here
in the order that they appear in the  menu. In each section, a short
description for each report is given, which explains what the report is
intended to show, and its primary purpose.

[[rpt_grp_assetsliabs]]

==== Assets &amp; Liabilities Group

Reports in this group provide general information about assets and liabilities.

[[rpt_advport]]

===== Advanced Portfolio

The Advanced Portfolio produces a report on commodity accounts
(stock and mutual fund type accounts) using price information stored in the
GnuCash price database and within the
GnuCash transaction data. If you do not have stock
price information in your file, the report will indicate an error. This report
includes extended information about commodity holdings, including information
about the basis, gain, and return of individual commodities.


++++++++++++++++++++++++++++++++++++++
<sect4 id="rpt-advport-capgains"><title>Advanced Portfolio Capital Gains</title><para>
      The Advanced Portfolio report doesn&rsquo;t use the capital gain splits to
      calculate capital gains. It calculates the gains from the various buy and
      sell transactions in the account without regard to whether the gains and
      losses are recorded or not. Any realized gain splits are ignored.
      Realized gain splits are recognized as two splits, one in the stock&rsquo;s
      account with a zero number of shares and a non-zero value, the other in an
      income or expense account with a value that is the negative of the split
      in the stock account. These two splits can be in a separate transaction
      (as created by scrubbing) or in the same transaction as the sale (this
      will cause incorrect future scrubbing). The income or expense split can
      be split into multiple splits, say for taxable/non-taxable or
      short/long term gains, without affecting this report.
    </para></sect4>
++++++++++++++++++++++++++++++++++++++
[[rpt_assetbarchart]]

===== Asset Barchart

The Asset Barchart presents the value of assets on a monthly basis in
barchart form. By default, the report displays the eight largest accounts that
have specific asset types assigned to them, and it displays bars for
the current financial period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Bars" option will display more bars in
the chart, allowing information for more accounts to display. Additionally,
the "Show table" option enables the display of chart information in tabular
form below the chart.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_assetpiechart]]

===== Asset Piechart

The Asset Piechart presents the value of assets on a monthly basis in
piechart form. By default, the report shows the seven largest accounts, that
have specific asset types assigned to them, arranged in descending order by
value as of the end of the current accounting period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Slices" option will display more
slices in the chart, allowing information for more accounts to display.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_avgbalance]]

===== Average Balance

The Average Balance report displays monthly averages for the current accounting period.

[[rpt_balancesheet]]

===== Balance Sheet

The Balance Sheet lists Asset, Liability, and Equity account balances
for all such accounts, and provides totals as of a given date. Balance sheets
are commonly run for the last day of each fiscal year to give an overall sense
of the financial condition of the entity.

[[rpt_generaljournal]]

===== General Journal

The General Journal produces a register of all transactions (beginning
to end) in order by date, showing the accounts and the amounts involved, and
totals the Net Change by all currencies and assets.

This report is not customizable by date or account, though you can
include more or fewer details about the individual transactions, and whether
to include running balances and totals for the credits and debits. If you
need a report restricted to particular accounts, consider the Transaction
Report or open a particular account and choose the Account Transaction Report.

[[rpt_generalledger]]

===== General Ledger

The General Ledger produces information about all transactions
for a selected set of accounts. When first run, this report loads no data,
and the report options must be changed to retrieve information from the file.

[[rpt_investport]]

===== Investment Portfolio

The Investment Portfolio produces a report of commodity accounts (that
is, accounts with type "Stock" or "Mutual Fund"), giving holdings, price and
value information about commodities in the file.

[[rpt_liabbarchart]]

===== Liability Barchart

The Liability Barchart presents the value of liabilities on a monthly basis in
barchart form. By default, the report displays the eight largest accounts that
have specific asset types assigned to them, and it displays bars for
the current financial period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Bars" option will display more bars in
the chart, allowing information for more accounts to display. Additionally,
the "Show table" option enables the display of chart information in tabular
form below the chart.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_liabpiechart]]

===== Liability Piechart

The Liability Piechart presents the value of liabilities on a monthly basis in
piechart form. By default, the report shows the seven largest accounts, that
have specific asset types assigned to them, arranged in descending order by
value as of the end of the current accounting period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Slices" option will display more
slices in the chart, allowing information for more accounts to display.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_networthbar]]

===== Net Worth Barchart

The Net Worth Barchart summarizes Asset accounts, Liability accounts, and
overall Net Worth as bars on a graph on a monthly basis for the current
financial period. This report provides a graphic overview of the file over time.

[[rpt_networthline]]

===== Net Worth Linechart

The Net Worth Linechart summarizes Asset accounts, Liability accounts, and
overall Net Worth as a line graph on a monthly basis for the current financial
period. This report provides a graphic overview of the file over time.

[[rpt_pricescatter]]

===== Price Scatterplot

The Price Scatterplot displays the value of one commodity relative to
another commodity, for example the value of a stock relative to a currency.
When first run, this report loads no data, and the report options must be
changed to retrieve information from the file. Specifically, the "Price of
Commodity" setting on the Price options tab must be changed to a specific
commodity.

[[rpt_grp_budget]]

==== Budget Group

 Budget reports in GnuCash allow you to gather
summary information related to budgets you may have created. In order for
these reports to work, you must first create a budget. The reports in this
group are specifically based on budget information. To use these reports, you
need to have a budget saved in your file.

[[rpt_budbalsht]]

===== Budget Balance Sheet



[[rpt_budbarchart]]

===== Budget Barchart



[[rpt_budflow]]

===== Budget Flow



[[rpt_budincstate]]

===== Budget Income Statement



[[rpt_budprofloss]]

===== Budget Profit &amp; Loss



[[rpt_budreport]]

===== Budget Report



[[rpt_grp_business]]

==== Business Group

Reports in this group provide general information about activities related
to a business.

[[rpt_customer]]

===== Customer Report



[[rpt_custsummary]]

===== Customer Summary

Customer Summary is a customer profit report that can help with job analysis by
comparing the income and expenses for a specific customer.

All invoices have an Owner in GnuCash, so invoices that are
made will show a customer and show in the report. When creating a Bill, the Default
Chargeback Customer is blank. To use the profit report, this field needs an entry,
since this is the tag that decides the line to which
to attach the expense. Left blank, the bill will be assigned to "No Customer."
Similarly, when income is entered directly in a register rather than creating an
invoice, it will also be assigned to "No Customer."

Thus, if this report includes an entry for "No Customer", this means that the report
may be inaccurate, as the results are not all properly labeled.

Possible use scenarios include:



** Tracking retail sales from different cities

** Tracking rental properties

** Tracking types of business

** Tracking commission sales


Each of these scenarios assumes that the account structure includes breakdowns
for individual tracked categories. Changing settings on the Income and Expense
tabs under Options can hone the information displayed. By default all income and
expense accounts are included; however, since GnuCash can't really predict
the names and classification of income and expense accounts, it must group them all
into the "No Customer" entry.

Note that inventory-based businesses won't benefit from this report because of its nature.

Useful options:



** The Expense Accounts tab allows the selection of one or more expense accounts.

** The Income Accounts tab allows the selection of one or more income accounts.

** The Display tab allows sorting by name, profit percentage, or amount of profit.


[[rpt_easyinv]]

===== Easy Invoice



[[rpt_employee]]

===== Employee Report



[[rpt_fancyinv]]

===== Fancy Invoice



[[rpt_payaging]]

===== Payable Aging



[[rpt_prtinv]]

===== Printable Invoice



[[rpt_recaging]]

===== Receivable Aging

This report provides a listing of all customers, their current balance, and
how much they have outstanding from invoices over different time periods&amp;mdash;how
much they owe from 0-30 days, from 31-60 days, from 61-90 days, and over 90 days.
The report also contains links to each customer and to their current customer report.

[[rpt_vendor]]

===== Vendor Report



[[rpt_grp_incexp]]

==== Income &amp; Expense Group

Reports in this group provide information about Income and Expense

[[rpt_cashflow]]

===== Cash Flow

This report shows the change in value for a set of accounts (the flow of cash)
over a given period of time. By default, this report is based on accounts in Assets and
Special Accounts, and covers the current financial period. The report enumerates
all money coming in to and going out of the base accounts, broken down by the
other account.

[[rpt_equity]]

===== Equity Statement

This report can be seen as extension of the Balance Sheet report. The
Balance Sheet states the balance of Assets, Liabilities and Equity at a
specific point of time. The Equity Statement focuses on the Equity Accounts
by showing the cash flow to and from them for a given period of time.

By balancing this cash flow with income, the report shows the available
capital at the beginning and end of the selected time period.

[[rpt_expbarchart]]

===== Expense Barchart

The Expense Barchart presents the value of expenses on a monthly basis in
barchart form. By default, the report displays the eight largest accounts that
have specific expense types assigned to them, and it displays bars for
the current financial period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Bars" option will display more bars in
the chart, allowing information for more accounts to display. Additionally,
the "Show table" option enables the display of chart information in tabular
form below the chart.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_exppiechart]]

===== Expense Piechart

The Expense Piechart presents the value of expenses on a monthly basis in
piechart form. By default, the report shows the seven largest accounts, that
have specific expense types assigned to them, arranged in descending order by
value as of the end of the current accounting period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Slices" option will display more
slices in the chart, allowing information for more accounts to display.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_expdayoweek]]

===== Expenses vs. Day of Week

Expenses vs. Day of Week presents a pie chart showing the totals for
selected expense accounts totaled by the day of the week of the transaction.
The report options enable you to make some adjustments (such as accounts,
display options, and the date range) but the account selector only allows
expense accounts to be chosen. The report aggregates expense transactions by
day of week, not by any other period or category. Due to these limitations,
the report may be considered a demonstration or an example to someone wanting
to examine the source code for composing a useful custom report.

[[rpt_incomebarchart]]

===== Income Barchart

The Income Barchart presents the value of income on a monthly basis in
barchart form. By default, the report displays the eight largest accounts that
have specific income types assigned to them, and it displays bars for
the current financial period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Bars" option will display more bars in
the chart, allowing information for more accounts to display. Additionally,
the "Show table" option enables the display of chart information in tabular
form below the chart.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_incexpchart]]

===== Income &amp; Expense Chart



[[rpt_incomepiechart]]

===== Income Piechart

The Income Piechart presents the value of income on a monthly basis in
piechart form. By default, the report shows the seven largest accounts, that
have specific income types assigned to them, arranged in descending order by
value as of the end of the current accounting period.

Several settings on this report can greatly affect the information included.



** On the Accounts tab, the "Show Accounts until level" option changes how
the report aggregates account totals. Change this value to see information at
deeper levels of the account structure.

** On the Display tab, the "Maximum Slices" option will display more
slices in the chart, allowing information for more accounts to display.

** On the General tab, the "Price Source" option can significantly
affect the reported value of various commodities included in the report.


[[rpt_incstatement]]

===== Income Statement

This report lists Income and Expense account totals for a set period. By
default, it shows all Expense and Income accounts down to 3 levels of
sub-accounts for the current financial period.

An Income Statement is also called a "Profit and Loss" report or "Revenue Statement."

In earlier versions of GnuCash, this report was called
"Profit &amp; Loss," but with version 2, the report was renamed "Income Statement"
to use more common accounting terminology.

The Income Statement helps show where money is coming from and where it is
going for a given time period.

[[rpt_incdayoweek]]

===== Income vs. Day of Week

Income vs. Day of Week presents a piechart showing the totals for selected
income accounts totaled by the day of the week of the transaction. The report
options enable you to make some adjustments (such as accounts, display options,
and the date range) but the account selector only allows income accounts to be
chosen. The report aggregates income transactions by day of week, not by any
other period or category. Due to these limitations, the report may be
considered a demonstration or an example to someone wanting to examine the
source code for composing a useful custom report.

[[rpt_trialbal]]

===== Trial Balance

Trial Balance lists the ending balances in all accounts as of a particular
date. It is typically run at the end of an accounting period and is primarily
used to ensure that the total of all debits equals the total of all credits.

[[rpt_grp_sampcust]]

==== Sample &amp; Custom Group

The reports in this group offer examples on how reports can be customized
or podified to suit personal need.

[[rpt_custommulti]]

===== Custom Multicolumn Report

This report provides a base that allows several standard and custom
reports to be combined into one view. Note that this report opens with an empty
window; you must open the options and designate which reports to include for display.
Once the reports have been selected, the settings for individual reports in the
multicolumn display can be edited.

[[rpt_sample]]

===== Sample Report with Examples

This is a sample report that users can examine to learn how to write their own reports.

[[rpt_welcome]]

===== Welcome Sample Report

This report demonstrates how the Multicolumn Report can be use to create
custom dashboard-type reports.

[[rpt_grp_miscrpts]]

==== Other Reports

Several reports are included on the main Reports menu. These are described
below.

[[rpt_acctsummary]]

===== Account Summary

This lists the balances of all accounts and subaccounts as of a
particular date. By default, this report shows accounts and totals
down to third-level subaccounts.

This report gives effectively the same information as the Chart of Accounts.
You can use this report to export and print the Chart of Accounts.

Note: To generate a report of account totals over a particular time period
(especially if you do not close your books at regular intervals), you might
consider using the Income Statement, or Cash Flow reports.

[[rpt_futsched]]

===== Future Scheduled Transactions Summary



[[rpt_taxtxf]]

===== Tax Report &amp; TXF Export

Generates a report and a downloadable .txf file of taxable income and
deductible expenses for a particular accounting period. To download the report
data, choose the Export button on the toolbar and choose between html and .txf
downloadable versions.

To use this report, you must use Edit --&gt; Tax Options to identify which
form the taxing authority uses for each income or expense account. Note that
you can see but not modify the "Tax related" checkbox in Edit --&gt; Edit Account.

[[rpt_txnrept]]

===== Transaction Report

This report lists the transactions in selected accounts during a
specified financial period. When first run, this report loads no data,
and the report options must be changed to retrieve information from the file.

[[rpt_savedrpts]]

===== Saved Report Configurations

Selecting this will open a dialog with a list of available Saved Report
Configurations. "Saved Report Configurations" means sets of customized
settings for standard reports.

These sets must be saved by the user before they appear here. See
Report Concepts above for instructions on how to save report configurations.

[[rpt_acctreport]]

===== Account Report

The Account Report menu entry only appears when an account register is
the active tab. This report produces a list of all transactions in the open
register.

Note that if you conduct a search that retrieves several transactions, the
results are displayed in a new search register, which can then be used to create
a report for just those transactions.

[[rpt_accttxnrept]]

===== Account Transaction Report

This report also only appears when an account register is the active tab.
However, this report only lists transactions that have been selected
(e.g. by mouse click) in the current register. If no transactions are selected,
an empty report will be generated.

