[[gnc-gloss]]
== GnuCash Glossary

[glossary]
This is a glossary of common terms used in GnuCash.
Some entries here are taken from Wikipedia (link:$$http://en.wikipedia.org$$[]).

[[gnc-gl_account]]
Account::
   An account keeps track of what you own, owe, spend or receive.

[[gnc-gl_accountingperiod]]
Accounting Period::
   An accounting period is the period with reference to which accounting 
books of an entity are prepared. Common accounting
periods include month, quarter, and year.

[[gnc-gl_aqbanking]]
AqBanking::
   A library which implements the German Home Banking Computer Interface 
(HBCI) and Electronic Banking Internet Communication Standard (EBICS), OFX 
Direct Connect and Paypal. It is the successor of openHBCI.

[[gnc-gl_asset]]
Asset::
   An asset is something you own. Anything tangible or intangible that 
can be owned or controlled to produce value and that is held to have 
positive economic value is considered an asset.

[[gnc-gl_balancesheet]]
Balance Sheet::
   A Balance Sheet is a summary of the financial balances of an individual 
or organization. It summarizes a company's assets, liabilities and ownership 
equity at a specific point in time.

[[gnc-gl_book]]
Book::
   A book is a record of all transactions for an individual or organization. In
GnuCash, each file contains a book.

[[gnc-gl_capgainloss]]
Capital Gain/Loss::
   The difference between the purchase and selling prices of an investment
at the time the investment is sold. Also known as 
__Realized Gain/Loss__. Before an investment 
is sold, the difference in value is referred to as 
__Unrealized Gain/Loss__.
+
See Also Realized Gain/Loss
+
See Also Unrealized Gain/Loss

[[gnc-gl_capstock]]
Capital stock::
   [[gnc-gl_chartofaccounts]]
Chart of Accounts::
   A listing of all the accounts available in the data file. The chart 
of accounts consists of balance sheet accounts (assets, liabilities, 
stockholders' equity) and income statement accounts (revenues, expenses, 
gains, losses).

[[gnc-gl_commission]]
Commission::
   The fee paid to a broker to buy or sell securities.

[[gnc-gl_commodity]]
Commodity::
   A commodity is something of value that is easily tradeable or sellable; 
for example, currencies, stocks, bonds, grain, copper, and oil are all commodities.

[[gnc-gl_commonstock]]
Common stock::
   [[gnc-gl_compounding]]
Compounding::
   The concept that the reinvested interest can later earn interest of 
its own (interest on interest). This is often referred to as __compound interest__.

[[gnc-gl_costbasis]]
Cost Basis::
   Cost basis is the original cost of property, adjusted for various factors. 
Its primary use is for tax purposes. Factors that affect the cost basis include: 
stock splits, dividends, depreciation and return of capital distributions. 
Cost basis is used to determine the __capital gain__.

[[gnc-gl_csv]]
CSV::
   Stands for Comma Separated Values. CSV files are used to store data 
in plain text. Each line of the file is a record and each record can be 
comprised of multiple fields separated by commas. CSV is one import format
that GnuCash supports.

[[gnc-gl_dividends]]
Dividends::
   Dividends are cash payments a company makes to shareholders. The 
amount of this payment is usually determined as some amount of the profits 
of the company. Not all common stocks give dividends.

[[gnc-gl_equities]]
Equities::
   Equities are investments in which the investor becomes part (or whole) 
owner in something.

[[gnc-gl_fints]]
Financial Transaction Services (FinTS)::
   A banking protocol used by German banks. Developed by the German Central 
Banking Committee ZKA (Zentraler Kredit-Ausschuss). The standard is used 
only by German banks. Prior 2002, it was called Home Banking Computer
Interface (HBCI). FinTS is one import format that GnuCash supports.
+
See Also Home Computer Banking Interface (HBCI)

[[gnc-gl_gsettings]]
GSettings::
   Since version 2.5 the tool that stores user configuration data. It 
uses the native data store of the operating system:

__Linux__:: DConf since Gnome 3.0 dropped GConf

__Mac OS X__:: Defaults. Use the command-line defaults(1) to modify 
prefs when GnuCash isn't running.

__Windows__:: Registry.

[[gnc-gl_hbci]]
Home Computer Banking Interface (HBCI)::
   A bank-independent online banking protocol used by German banks. Home 
Banking Computer Interface (HBCI) was developed by the German Central 
Banking Committee ZKA (Zentraler Kredit-Ausschuss). Since 2002, it has 
been called Financial Transaction Services (FinTS). HBCI is one import 
format that GnuCash supports.
+
See Also Financial Transaction Services (FinTS)

[[gnc-gl_interest]]
Interest::
   What a borrower pays a lender for the use of their money. Normally, 
this is expressed in terms of a percentage of the principal per year. For 
example, a savings account with 1% interest will pay you $1 for every $100 
you keep deposited per year.

[[gnc-gl_liability]]
Liability::
   A liability is a debt or obligation that an individual or organization
owes.

[[gnc-gl_libofx]]
LibOFX::
   An open source library for __OFX__. It was created by one 
of the GnuCash developers, originally to be the 
OFX interface for GnuCash.
+
See Also OFX

[[gnc-gl_liquidity]]
Liquidity::
   A measure of how easily convertible an investment is to cash. Money 
in a savings account is very liquid, while money invested in a house has 
low liquidity because it takes time to sell a house.

[[gnc-gl_lot]]
Lot::
   A lot is a means of grouping a commodity so that you later identify that 
the item bought in one transaction is the same as one sold in a different 
transaction. Lots are often implemented with stocks, where capital gain can
depend on which item is being sold at a given time.

[[gnc-gl_mt940]]
MT940::
   A financial information standard defined by SWIFT and used by several 
European banks. It is also used internally in HBCI. Unfortunately, you can't 
download the MT940 standard, but some banks publish it on their web sites. 
MT940 is one import format that GnuCash supports.

[[gnc-gl_ofx]]
OFX::
   The Open Financial eXchange format. This is a financial information 
exchange standard used by many institutions. OFX is one import format
that GnuCash supports.

[[gnc-gl_pricedb]]
Price Database::
   The price database contains a store of price quotes for stocks, mutual
funds, and currencies.

[[gnc-gl_principal]]
Principal::
   The original amount of money invested or borrowed.

[[gnc-gl_qfx]]
QFX::
   The Quicken Financial eXchange format is a proprietary financial 
information exchange standard promoted by Quicken and used by many institutions. 
QFX is one import format that GnuCash supports.

[[gnc-gl_qif]]
QIF::
   The Quicken Interchange Format (QIF) is an open specification for 
reading and writing financial data to files. This is an older format that 
is still used by many institutions. QIF is one import format
that GnuCash supports.

[[gnc-gl_realgainloss]]
Realized Gain/Loss::
   The difference between the purchase and selling prices of an investment
at the time the investment is sold. Also known as 
__Capital Gain/Loss__. Before an investment 
is sold, the difference in value is referred to as 
__Unrealized Gain/Loss__.
+
See Also Capital Gain/Loss
+
See Also Unrealized Gain/Loss

[[gnc-gl_return]]
Return::
   The total income plus capital gains or losses of an investment.
+
See Also Yield

[[gnc-gl_reversingtxn]]
Reversing Transaction::
   In formal accounting, a transaction is never deleted. Therefore, when
a mistake is made, the original transaction remains in the ledger, and a
transaction is added to the ledger that reverses the original. This 
__reversing transaction__ duplicates the original transaction, 
but with debit and credit amounts reversed. This removes the effect of the 
erroneous transaction from the books. After entering the reversing transaction, 
a corrected transaction can then be entered. Reversing
transactions are not commonly used in personal accounting.

[[gnc-gl_risk]]
Risk::
   The probability that the return on investment is different from what 
was expected. Investments are often grouped on a scale from low risk (e.g., 
savings accounts or government bonds) to high risk (e.g., common stocks 
or junk bonds). As a general rule of thumb, the higher the risk, the 
higher the possible return.

[[gnc-gl_schedtxn]]
Scheduled Transaction::
   Scheduled transactions provide a framework for remembering information 
about transactions that are set to occur in the future, either once or 
periodically.
+
See Also Yield

[[gnc-gl_scheme]]
Scheme::
   Scheme is a functional programming language based on a dialect of LISP.
Reports in GnuCash use the Scheme programming language;
thus, users wishing to customize reports must write Scheme.

[[gnc-gl_shareholder]]
Shareholder::
   A shareholder is a person who holds common stock in a company.

[[gnc-gl_split]]
Split::
   A split, or Ledger Entry, is the fundamental accounting unit. 
Each split consists of an amount, the value of that amount expressed in a 
(possibly) different currency, a Memo, a pointer to the parent Transaction, 
a pointer to the debited Account, a reconciled flag and timestamp, an action 
field, and a key-value frame which can store arbitrary data.

[[gnc-gl_stock]]
Stock::
   A security that represents a certain fractional ownership of a company. 
This is what you buy when you "buy stock" in a company on the 
open market. This is also sometimes known as __capital stock__, 
or __common stock__.

[[gnc-gl_stocksplit]]
Stock split::
   Occurs when a company offers to issue some additional multiple of shares 
for each existing stock. For example, a "2 for 1" stock split 
means that if you own 100 shares of a stock, you will receive an additional 
100 shares at no cost to you. The unit price of the shares will usually be 
adjusted  so there is no net change in the value, so in this example the 
price per share will be halved. Note that such transactions affect the cost
basis per share owned.

[[gnc-gl_transaction]]
Transaction::
   A transaction consists of a date, a description, an ID number, a list 
of two or more splits, and a key-value frame. Transactions embody the notion 
of "double entry" accounting.

[[gnc-gl_unrealgainloss]]
Unrealized Gain/Loss::
   Unrealized gain or loss is the difference in value between a purchase
price and the current value of a given asset. These gains remain unrealized
until the asset is sold, at which point they become __Realized gains or losses__.
+
See Also Capital Gain/Loss
+
See Also Realized Gain/Loss

[[gnc-gl_valuation]]
Valuation::
   The process of determining the market value or the price the 
investment would sell at in a "reasonable time frame".

[[gnc-gl_xml]]
XML::
   The eXtensible Markup Language is an international markup standard.
GnuCash stores its data by default in an XML data 
structure.

[[gnc-gl_yield]]
Yield::
   A measure of the amount of money you earn from an investment 
(i.e., how much income you receive from the investment). Typically, this 
is reported as a percentage of the principal amount. Yield does not include 
capital gains or losses (see Return). For example, a stock that sells for $100 
and gives $2 in dividends per year has a yield of 2%.

