= GnuCash Tutorial and Concepts Guide

*THIS IS NOT OFFICIAL DOCUMENTATION! Please see the main GnuCash website at http://www.gnucash.org*

== Author

The GnuCash Documentation Team
This Guide contains a tutorial for using GnuCash and describes the concepts behind GnuCash.

== Copyright

Copyright © 2009-2017 GnuCash Documentation Team

Copyright © 2010-2011 Yawar Amin

Copyright © 2010 Tom Bullock

Copyright © 2010-2011 Cristian Marchi

Copyright © 2006 Chris Lyttle

Copyright © 2003-2004 Jon Lapham

Copyright © 2002 Chris Lyttle

Copyright © 2001 Carol Champagne and Chris Lyttle

== Legal Notice

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License (GFDL), Version
1.1 or any later version published by the Free Software Foundation
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
Texts. You can find a copy of the GFDL at this link or in the file
COPYING-DOCS distributed with this manual.

This manual is part of a collection of GNOME manuals distributed under
the GFDL. If you want to distribute this manual separately from the
collection, you can do so by adding a copy of the license to the
manual, as described in section 6 of the license.

Many of the names used by companies to distinguish their products and
services are claimed as trademarks. Where those names appear in any
GNOME documentation, and the members of the GNOME Documentation
Project are made aware of those trademarks, then the names are in
capital letters or initial capital letters.

DOCUMENT AND MODIFIED VERSIONS OF THE DOCUMENT ARE PROVIDED UNDER THE
TERMS OF THE GNU FREE DOCUMENTATION LICENSE WITH THE FURTHER
UNDERSTANDING THAT:

DOCUMENT IS PROVIDED ON AN “AS IS” BASIS, WITHOUT WARRANTY OF ANY
KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION,
WARRANTIES THAT THE DOCUMENT OR MODIFIED VERSION OF THE DOCUMENT IS
FREE OF DEFECTS MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE OR
NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY, ACCURACY, AND
PERFORMANCE OF THE DOCUMENT OR MODIFIED VERSION OF THE DOCUMENT IS
WITH YOU. SHOULD ANY DOCUMENT OR MODIFIED VERSION PROVE DEFECTIVE IN
ANY RESPECT, YOU (NOT THE INITIAL WRITER, AUTHOR OR ANY CONTRIBUTOR)
ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION. THIS
DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE.
NO USE OF ANY DOCUMENT OR MODIFIED VERSION OF THE DOCUMENT IS
AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER; AND

UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER IN TORT (INCLUDING NEGLIGENCE), CONTRACT, OR OTHERWISE, SHALL THE AUTHOR, INITIAL WRITER, ANY CONTRIBUTOR, OR ANY DISTRIBUTOR OF THE DOCUMENT OR MODIFIED VERSION OF THE DOCUMENT, OR ANY SUPPLIER OF ANY OF SUCH PARTIES, BE LIABLE TO ANY PERSON FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER DAMAGES OR LOSSES ARISING OUT OF OR RELATING TO USE OF THE DOCUMENT AND MODIFIED VERSIONS OF THE DOCUMENT, EVEN IF SUCH PARTY SHALL HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.

== Feedback

To report a bug or make a suggestion regarding this package or this manual, follow the directions at the GNOME Bug Tracking System.

== History

|===
|Title|Date|Author|Publisher
|GnuCash Tutorial and Concepts Guide v2.6.15|26 March 2017    |Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.6.11|11 January 2016  |Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.6.8 |27 September 2015|Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.6.7 |28 June 2015     |Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.6.3 |30 March 2014    |Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.6.2 |2 March 2014     |Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.6.1|26 January 2014|Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.6.0|29 December 2013|Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.4.2|17 November 2012|Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.4.1|1 July 2011|Multiple authors|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.3.16|November 7, 2010|Jon Lapham, Bengt Thuree, Dave Herman|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v2.0.0|July 2006|Jon Lapham, Bengt Thuree, Dave Herman|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v1.8.3|Aug 2003|Jon Lapham|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v1.8.2|Aug 2003|Jon Lapham|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v1.8.1|May 2003|Chris Lyttle|GnuCash Documentation Team
|GnuCash Tutorial and Concepts Guide v1.8.0|Jan 2003|Chris Lyttle|GnuCash Documentation Team
|GnuCash User Guide v1.6.5|June 2002|Chris Lyttle|GnuCash Documentation Team
|GnuCash User Guide v1.6.0|October 2001|Carol Champagne|GnuCash Documentation Team
