[[chapter_expenses]]

== Aufwandskonten

Um Ihr Girokonto zu bewirtschaften, ist der erste Schritt, Ihre Finanzen 
zu verfolgen. Der naheliegende zweite Schritt, um zu sehen, wo Sie Geld 
ausgeben, ist die Nutzung von Aufwandskonten. Dieses Kapitel vermittelt Ihnen, 
wie GnuCash Aufwandskonten nutzt, 
um Ihnen zu helfen, die Übersicht über die verschiedenen Buchungskategorien 
zu behalten.

[[expenses-concepts]]

=== Konzepte

Ein Aufwandskontentyp erlaubt Ihnen aufzuzeichnen, wie viel Sie für bestimmte 
Ausgaben aufwenden. Formal sind Aufwandskonten kein Teil der herkömmlichen Buchhaltung; 
aber sie wurden mit der zunehmenden Verfügbarkeit computergestützter Buchhaltungssysteme 
gebräuchlich. Die erste Erfahrung mit der Aufzeichnung des Aufwandes machten viele mit 
Quicken(tm). Dort können die Buchungen einer oder mehreren Kategorien zugeordnet werden. 
In GnuCash sind diese Kategorien als separate Konten eingerichtet. 
Das erlaubt GnuCash, die Regeln der doppelten Buchführung 
einheitlich anzuwenden. Aufwandskonten können so allgemein oder detailliert sein, 
wie Sie es benötigen. einige Nutzer benötigen nur wenige Konten für ihre persönliche 
Aufzeichnung des Aufwandes. Andere nutzen Aufwandskonten in GnuCash, 
um ihren Aufwand in allen Einzelheiten zu kontrollieren. Die Detailtiefe bestimmen 
Sie selber. Beachten Sie, dass Sie mit GnuCash die Konten 
für die Buchungen ändern können, wenn Sie später Änderungen benötigen. Dann ist es noch möglich, 
Buchungen zu verschieben.

[[expenses-setup]]

=== Konteneinrichten

[[expenses-su-simple]]

==== Einfache Einrichtung der Aufwandskonten

Für viele Nutzer ist der einfachste Weg, Aufwandskonten einzurichten, die 
"Allgemeinen Konten" zu prüfen, wenn Sie eine neue kontenhierarchie erstellen.
Dies wird Ihnen die meisten Aufwandskonten erstellen, die Sie benötigen.
Für mehr Informationen schauen Sie auch unter "New Account Hierarchy Setup" 
in Kapitel 3 der Hilfe (en).

[[expenses-su-complex]]

==== Umfangreiche Einrichtung der Aufwandskonten

Wenn Sie verschieden Aufwandskonten benötigen, können Sie sich auf <<chapter_txns>> 
oder Kapitel 5.4 in der Hilfe (en) beziehen.

Klassische Gründe, neue oder verschiedne Konten hinzuzufügen, schließen ein:
aufzeichnen bestimmter Geschäftsvorfälle (z.B. spezielle Arten des Beschaffungsaufwandes),
aufzeichnen bestimmter Steuertatbestände (z.B. Steueraufwand muss anderen berichtet werden),
oder einfach Aufwand aufzeichnen, das es für Sie aussagekräftig ist (z.B. Zahlung an eine 
bestimmte gemeinützige Organisation).

[[expenses-entering]]

=== Eingabe der Aufwandsbuchungen

Während es möglich ist, Buchungen direkt in die Aufwandskonten einzugeben, 
ist es, ist es nicht normal, wie diese einzugeben sind. Für die meisten Leute werden die 
Buchungen für ein Aufwandskonto hinzugefügt, wenn der Nutzer Daten in ein 
anderesn Konto in der Buchung eingibt. Mit anderen Worten: wenn Sie ein Aufwandskonto 
für gemeinnützige Spenden haben (z.B. Aufwendungen:Spenden), werden Sie normalerweise
eine Buchung dem Aufwandskonto hinzufügen, indem Sie die Buchung auf dem Girokonto dem 
Spendenkonto zuweisen.

Wenn Sie ein Aufwandskonto öffnen, werden Sie ein Kontenblatt sehen, wie Sie 
es auch an den anderen Stellen in GnuCash finden. Die 
formlosen Spaltenköpfe für die Buchungsbeträge sind ein wenige verschieden. 
Die linke Spalte (Aufwand) wird als __Gesamtaufwand__ gelesen, während 
die rechte Spalte (Erstattung) als __Gesamterstattung__ gelesen wird.

[[expenses-other]]

=== Weitere Überlegungen für Aufwandskonten

Weil Aufwandskonten ganz von Ihnen erstellt werden, gibt es keine Bankauszüge, 
gegen die Sie Ihre Daten abgleichen können. Daher gibt es streng genommen nichts abzugleichen.
Sie können das Abgleichprozedere für Aufwandskonten dazu nutzen, dass die 
Buchungen vor spätere Eingaben geschützt sind. 

Eins sollten Sie bedenken, dass durch Ihre weitere Nutzung von GnuCash 
der Saldo dieser Konten wächst, weil es nur sehr wenige Erstattungsbuchungen gibt, 
die den Saldo erniedrigen. Daran ist nichts falsch. Aber einige Nutzer möchten regelmäßig 
die Salden ihrer Aufwandskonten leeren. Solche Buchungen können eingegeben werden, indem 
der Kontensaldo auf ein Eigenkapitalskonto übertragen wird. GnuCash 
beinhaltet auch ein Verfaren zum Buchungsabschluss, dass die Aufwandskonten auf Null (0,00) setzt. 
Beachten Sie, dass dies nicht notwendig ist. Wenn Sie dies benötigen, um bestimmte 
Informationen von einem Aufwandskonto zu erhalten, können Sie auch die verschiedenen Reporte nutzen.

