
[appendix]
== Anhang E

[[appendixe]]

=== Kommandozeilen Optionen


----

$ gnucash --help-all
Aufruf:
  gnucash [OPTION …]  [datafile]

Hilfeoptionen:
  -h, --help                   Hilfeoptionen anzeigen
  --help-all                   Alle Hilfeoptionen anzeigen
  --help-gtk                   GTK+-Optionen anzeigen

GTK+-Optionen
  --class=KLASSE               Programmklasse, die vom Fenstermanager benutzt wird
  --name=NAME                  Programmname, der vom Fenstermanager benutzt wird
  --screen=BILDSCHIRM          X-Bildschirm, der verwendet werden soll
  --sync                       X-Aufrufe synchron verarbeiten
  --gtk-module=MODULE          Zusätzliche GTK+-Module laden
  --g-fatal-warnings           Alle Warnungen als fatal betrachten

Anwendungsoptionen:
  -v, --version                GnuCash Version anzeigen
  --debug                      Debug-Modus aktivieren: Besonders viele Log-Meldungen ausgeben.
  --extra                      Zusätzliche/instabile/Debug-Funktionen aktivieren.
  --log                        Loglevel einstellen; Beispiel »komponente.irgendwas=
                                 {debug,info,warn,crit,error}«
  --logto                      Datei, wo die Logmeldungen hingeschrieben werden; Voreinstellung 
                                 "/tmp/gnucash.trace"; kann auch "stderr" oder "stdout" sein.
  --nofile                     Zuletzt geöffnete Datei nicht öffnen
  --gconf-path=GCONFPFAD       Suchpfad für gconf-Abfragen setzen
  --add-price-quotes=DATEI     Börsenkurse zu angegebener Datei hinzufügen
  --namespace=REGEXP           Regulärer Ausdruck für den Namensstandard, in dem die Kurse 
                                 geholt werden sollen
  --display=ANZEIGE            X-Anzeige, die verwendet werden soll

----


=== Aufgaben, Menüs und Kurzwahl Tastenkombinationen.


Nach Buchungen suchen +
menu:Bearbeiten[StrgfSuchen…] +
Neue Datei +
menu:Datei[StrgnNeu &gt; Neue Datei] +
Datei öffnen +
menu:Datei[StrgoÖffnen &gt; Öffnen] +
Datei speichern +
menu:Datei[StrgsSpeichern] +
Datei speichern unter… +
menu:Datei[ShiftStrgsSpeichern] +
Buchung eingeben +
menu:Aktionen[StrgtBuchen…] +
Ausgewähltes Konto löschen +
menu:Bearbeiten[EntfKonto löschen…] +
Ausgewähltes Konto bearbeiten +
menu:Bearbeiten[StrgeKonto bearbeiten] +
In der Buchungsansicht ausgewählten Text ausschneiden +
menu:Bearbeiten[StrgxAusschneiden] +
In der Buchungsansicht ausgewählten Text kopieren +
menu:Bearbeiten[StrgcKopieren] +
In der Buchungsansicht kopierten Text einfügen +
menu:Bearbeiten[StrgvEinfügen] +
Registerkarte schließen +
menu:Datei[StrgwSchließen] +
Seite einrichten +
menu:Datei[ShiftStrgpSeite einrichten] +
Schecks oder Berichte drucken +
menu:Datei[StrgpDrucken] +
Datei Eigenschaften bearbeiten +
menu:Datei[AltReturnEigenschaften] +
GnuCash beenden +
menu:Datei[StrgqBeenden] +
GnuCash Hilfe aufrufen +
menu:Hilfe[F1Inhalt] +
Ansicht aktualisieren +
menu:Ansicht[StrgrAktualisieren]




GnuCash speichert diese Tastenkombinationen in der Datei __accelerator-map__ 
im dem versteckten Ordner __.gnucash__ in Ihrem persönlichen Verzeichnis.


++++++++++++++++++++++++++++++++++++++
<!-- TODO how to add personal shortcuts -->
++++++++++++++++++++++++++++++++++++++
    


